spring:
  # 데이터 베이스 설정
  datasource:
    url: jdbc:mysql://localhost:3306/cozy?serverTimezone=UTC&characterEncoding=UTF-8
    username: cozy
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
